### ISSUE TITLE
Fix SQL key clash bug

### ISSUE THREAD

**Issue by Moosichu** [HackCambridge/website#1]
There is a horrible error message if you submit the same email more than once. Fix it to make it nicer!

**Comment by wlyinan** [comment]
people can't drop table or anything like that with SQL database right?

**Comment by Moosichu** [comment]
No, it's a safe error. It's just a pretty printing issue. 

The code isn't prone to SQL injections and the password is the backend is not world-readable.

**Comment by Moosichu** [comment]
Fixed.
