### ISSUE TITLE
Facebook/ Twitter

### ISSUE THREAD

**Issue by a96tudor** [HackCambridge/website#2]
The Facebook and Twitter tabs are not working.
It gives me an error

<img width="1166" alt="screen shot 2015-10-27 at 22 04 35" src="https://cloud.githubusercontent.com/assets/15090742/10774030/c884418a-7cf6-11e5-998f-0d2854ed26ff.png">

**Comment by Pinpickle** [comment]
Oh whoops, I didn't put in the links. They're just placeholders haha.

Pinging @Moosichu

**Comment by Moosichu** [comment]
Fixed in the code! So when the next upgrade is done the links will be correct!
